set nu smartindent  expandtab tabstop=4 shiftwidth=4 softtabstop=4
set pastetoggle=<F2>
colo murphy

" Map keys
nnoremap <F8> :colo murphy<CR>
nnoremap <S-F8> :colo evening<CR>
nnoremap <F9> :colo torte<CR>
nnoremap <S-F9> :colo ron<CR>

noremap <S-F11> :set encoding=utf-8<CR>

" Trailing whitespace.
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufEnter * match ExtraWhitespace /\s\+$/
if version >= 700
    autocmd ColorScheme * highlight ExtraWhitespace guibg=red
    autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
    autocmd InsertLeave * match ExtraWhiteSpace /\s\+$/
endif
